version: '2'
networks:
  keycloak-network:
    name: keycloak-network
services:
  postgres:
    image: postgres
    networks:
      - keycloak-network
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postresql/data/pgdata
    ports:
    - 5434:5434
    container_name: local_postgres_kc
  keycloak:
    image: cogniti/keycloak-custom-theme
    networks:
      - keycloak-network
    depends_on:
      - postgres
    environment:
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
    - 8080:8080
#    - 8282:8080